### ISSUE TITLE
Points in 3D space

### ISSUE THREAD

**Issue by jamalknight** [CAMMA-public/ORPose-Color#1]
Hi there

Is there an option in this code to output the keypoints as 3D space coordinates (x,y and z) ?

Regards,
Jamal

**Comment by vinkle** [comment]
Hi Jamal,
You can use `pred_keypoints_h36_3d` to get the 3D coordinates in root-relative human3.6 format .
https://github.com/CAMMA-public/ORPose-Color/blob/4efe8c3ed1239b4ff4a41e1366e2f84cddcadf67/keypoints_3d/keypoints3d_head.py#L269

example code:
`CONFIG_FILE = "configs/orpose_fixed_12x.yaml"`
`MODEL_WEIGHTS = "path to weights"`
`cfg = get_cfg()`
`add_keypoints3d_config(cfg)`
`cfg.merge_from_file(CONFIG_FILE)`
`cfg.MODEL.WEIGHTS = MODEL_WEIGHTS`
`cfg.DATASETS.H36_STATS_PATH = H36_STATS_FILE`
`predictor = DefaultPredictor(cfg)`
`predictions = predictor(img_sr)`
`keypoints3d_h36 =  np.asarray(predictions.pred_keypoints_h36_3d) # 3d points in root-relative human3.6 format`

**Comment by jamalknight** [comment]
Thank you
